import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "@/components/partial/layout/Layout";
import { DarkModeProvider } from "@/core/provider/DarkModeProvider";
import { ThemeProvider } from "@/core/provider/ThemeContext";
import { CalendarProvider } from "@/core/provider/CalendarContext";
import { WorkSpaceProvider } from "@/core/provider/WorkSpaceContext";
import StoreProvider from "@/core/provider/StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          <StoreProvider>
            <ThemeProvider>
              <DarkModeProvider>
                <CalendarProvider>
                  <WorkSpaceProvider>
                    <Layout>{children}</Layout>
                  </WorkSpaceProvider>
                </CalendarProvider>
              </DarkModeProvider>
            </ThemeProvider>
          </StoreProvider>
      </body>
    </html>
  );
}
